/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/app-footer.vue')['default']
    AppLayout: typeof import('./src/components/layout/app-layout.vue')['default']
    GithubLogo: typeof import('./src/components/github-logo.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IFluentWallet28Regular: typeof import('~icons/fluent/wallet28-regular')['default']
    IFluentWeatherMoon20Regular: typeof import('~icons/fluent/weather-moon20-regular')['default']
    IFluentWeatherSunny20Regular: typeof import('~icons/fluent/weather-sunny20-regular')['default']
    ProviderConnectButton: typeof import('./src/components/provider-connect-button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
